# Site setings
name: "My Personal Portfolio"
description: "I wanted to find a place where I could put all my projects and display them properly, so here it is, please enjoy!"
meta_description: "Jekyll template, minimal style, perfect for bloggers."
logo: 'assets/images/namelogo.png'
favicon: 'assets/images/pagefavicon.ico'
baseurl:
production_url: https://horace.netlify.com/
disqus: 'justgoodthemes'
cover_image: bc_1.jpg

# Author
author:
    name: "Alejandro Isa Adaniya"
    image: "asd.jpg"
    greetings: "Welcome to my Portfolio!"
    description: "My name is Alejandro Isa. This is where you will find personal projects I have worked on and other projects I am learning about.\n Enjoy!"
    bio: "Alejandro is a graduated computer scientist from Memorial University of Newfoundland. Passions include coding and interface design."

# Social links
twitter:
facebook:
googleplus:
github: "aisaadaniya"
codepen:
dribbble:
medium:
instagram:
pinterest:
linkedin: "aisaadaniya"

navigation:
- text: About
  url: /about/
- text: Style Guide
  url: /style-guide/
- text: LiteBrite
  url: /litebrite/
- text: Resume
  url: /resume/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
    sass_dir: _sass
    style: compressed
